# -*- mode: ruby -*-
# vi: set ft=ruby :
boxes = [
    {
        :name => "k8s-1",
        :eth1 => "192.168.205.10",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "k8s-2",
        :eth1 => "192.168.205.11",
        :mem => "512",
        :cpu => "2"
    },
    {
        :name => "k8s-3",
        :eth1 => "192.168.205.12",
        :mem => "512",
        :cpu => "2"
    }
]

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.provider "vmware_fusion" do |v|
          v.vmx["memsize"] = opts[:mem]
          v.vmx["num:qvcpus"] = opts[:cpu]
        end
        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        end
        config.vm.network :private_network, ip: opts[:eth1]
      end
        config.vm.provision "shell", inline: <<-SHELL
          apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl enable --now docker
        SHELL
  end
end